namespace AnaPrevention.GeneralMasterData.Api.ServiceCatalogs.Domain.Enums
{
    public enum MedicalFormSubType
    {
        NONE = 0,
        OCCUPATIONAL_HISTORY_PERSONAL = 1,
        OCCUPATIONAL_HISTORY_RISK = 2,
        OCCUPATIONAL_HISTORY_VACCINE = 3,
        OCCUPATIONAL_HISTORY_HABIT = 4,
        OCCUPATIONAL_HISTORY_FAMILY = 5,
        OCCUPATIONAL_HISTORY_SURGICAL = 6,
        OCCUPATIONAL_HISTORY_REPRODUCTIVE = 7,
        OCCUPATIONAL_HISTORY_ACCIDENT_DISEASE = 8,
        OCCUPATIONAL_HISTORY_PATHOLOGICAL = 9,
        OCCUPATIONAL_HISTORY_CARDIO_VASCULAR = 10,
    }
}
